# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

parameters:
- name: publishBuild
  displayName: Publish new build?
  type: boolean
  default: false

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'outsystemsrd'
    scannerMode: 'CLI'
    configMode: 'file'
- task: Gradle@2
  displayName: Build Project
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx4096M'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'clean build'
- task: CmdLine@2
  displayName: Validate pom.xml
  inputs:
    script: |
      /usr/bin/mvn -version
      /usr/bin/mvn -f /home/vsts/work/1/s/pom.xml help:effective-pom
- task: MavenAuthenticate@0
  displayName: Authenticate in public repo
  condition: or(${{parameters.publishBuild}}, eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    artifactsFeeds: 'PublicArtifactRepository'
- task: Bash@3
  displayName: Deploy file
  condition: or(${{parameters.publishBuild}}, eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  inputs:
    targetType: 'inline'
    script: |
      /usr/bin/mvn deploy:deploy-file \
      -DpomFile=/home/vsts/work/1/s/pom.xml \
      -DgeneratePom=true \
      -Dfile=build/outputs/aar/OSBarcodeLib-release.aar \
      -Dpackaging=aar \
      -DrepositoryId=PublicArtifactRepository \
      -Durl=https://pkgs.dev.azure.com/OutSystemsRD/9e79bc5b-69b2-4476-9ca5-d67594972a52/_packaging/PublicArtifactRepository/maven/v1