name: Publish Native Android Library

on: workflow_dispatch

jobs:
  publish-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Grant execute permission for publishing script
        run: chmod +x ./scripts/publish-android.sh
      - name: Make local props
        run: |
          cat << EOF > "local.properties"
          ossrhUsername=${{ secrets.ANDROID_OSSRH_USERNAME }}
          ossrhPassword=${{ secrets.ANDROID_OSSRH_PASSWORD }}
          sonatypeStagingProfileId=${{ secrets.ANDROID_SONATYPE_STAGING_PROFILE_ID }}
          signing.keyId=${{ secrets.ANDROID_SIGNING_KEY_ID }}
          signing.password=${{ secrets.ANDROID_SIGNING_PASSWORD }}
          signing.key=${{ secrets.ANDROID_SIGNING_KEY }}
          EOF
          echo "local.properties file has been created successfully."
      - name: Run publish script
        working-directory: ./scripts
        run: ./publish-android.sh